// Generated by TinyPG v1.3 available at www.codeproject.com

using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Xml.Serialization;

namespace parser
{
    #region Scanner

    public partial class Scanner
    {
        public string Input;
        public int StartPos = 0;
        public int EndPos = 0;
        public int CurrentLine;
        public int CurrentColumn;
        public int CurrentPosition;
        public List<Token> Skipped; // tokens that were skipped
        public Dictionary<TokenType, Regex> Patterns;

        private Token LookAheadToken;
        private List<TokenType> Tokens;
        private List<TokenType> SkipList; // tokens to be skipped

        public Scanner()
        {
            Regex regex;
            Patterns = new Dictionary<TokenType, Regex>();
            Tokens = new List<TokenType>();
            LookAheadToken = null;
            Skipped = new List<Token>();

            SkipList = new List<TokenType>();
            SkipList.Add(TokenType.WHITESPACE);

            regex = new Regex(@"(0|1)");
            Patterns.Add(TokenType.ALIGNMENT, regex);
            Tokens.Add(TokenType.ALIGNMENT);

            regex = new Regex(@"[0-9]+");
            Patterns.Add(TokenType.UINT, regex);
            Tokens.Add(TokenType.UINT);

            regex = new Regex(@"(-)?[0-9]+");
            Patterns.Add(TokenType.INT, regex);
            Tokens.Add(TokenType.INT);

            regex = new Regex(@"([0-9]+(\.[0-9]*)?|\.[0-9]+)");
            Patterns.Add(TokenType.UFLOAT, regex);
            Tokens.Add(TokenType.UFLOAT);

            regex = new Regex(@"(x|y|z|X|Y|Z)");
            Patterns.Add(TokenType.AXIS, regex);
            Tokens.Add(TokenType.AXIS);

            regex = new Regex(@"color");
            Patterns.Add(TokenType.COLOR, regex);
            Tokens.Add(TokenType.COLOR);

            regex = new Regex(@"piece");
            Patterns.Add(TokenType.PIECE, regex);
            Tokens.Add(TokenType.PIECE);

            regex = new Regex(@"tube");
            Patterns.Add(TokenType.TUBE, regex);
            Tokens.Add(TokenType.TUBE);

            regex = new Regex(@"cap");
            Patterns.Add(TokenType.CAP, regex);
            Tokens.Add(TokenType.CAP);

            regex = new Regex(@"injector");
            Patterns.Add(TokenType.INJECTOR, regex);
            Tokens.Add(TokenType.INJECTOR);

            regex = new Regex(@"(.*\r?\n\r?)+");
            Patterns.Add(TokenType.IGNOREDSTUFF, regex);
            Tokens.Add(TokenType.IGNOREDSTUFF);

            regex = new Regex(@"end");
            Patterns.Add(TokenType.END, regex);
            Tokens.Add(TokenType.END);

            regex = new Regex(@"^$");
            Patterns.Add(TokenType.EOF, regex);
            Tokens.Add(TokenType.EOF);

            regex = new Regex(@"time");
            Patterns.Add(TokenType.TIME, regex);
            Tokens.Add(TokenType.TIME);

            regex = new Regex(@"(\+|-)+");
            Patterns.Add(TokenType.SIGN, regex);
            Tokens.Add(TokenType.SIGN);

            regex = new Regex(@"injection");
            Patterns.Add(TokenType.INJECTION, regex);
            Tokens.Add(TokenType.INJECTION);

            regex = new Regex(@"tags");
            Patterns.Add(TokenType.TAGS, regex);
            Tokens.Add(TokenType.TAGS);

            regex = new Regex(@"\(");
            Patterns.Add(TokenType.BROPEN, regex);
            Tokens.Add(TokenType.BROPEN);

            regex = new Regex(@"\)");
            Patterns.Add(TokenType.BRCLOSE, regex);
            Tokens.Add(TokenType.BRCLOSE);

            regex = new Regex(@"\,");
            Patterns.Add(TokenType.COMMA, regex);
            Tokens.Add(TokenType.COMMA);

            regex = new Regex(@"\s+");
            Patterns.Add(TokenType.WHITESPACE, regex);
            Tokens.Add(TokenType.WHITESPACE);


        }

        public void Init(string input)
        {
            this.Input = input;
            StartPos = 0;
            EndPos = 0;
            CurrentLine = 0;
            CurrentColumn = 0;
            CurrentPosition = 0;
            LookAheadToken = null;
        }

        public Token GetToken(TokenType type)
        {
            Token t = new Token(this.StartPos, this.EndPos);
            t.Type = type;
            return t;
        }

         /// <summary>
        /// executes a lookahead of the next token
        /// and will advance the scan on the input string
        /// </summary>
        /// <returns></returns>
        public Token Scan(params TokenType[] expectedtokens)
        {
            Token tok = LookAhead(expectedtokens); // temporarely retrieve the lookahead
            LookAheadToken = null; // reset lookahead token, so scanning will continue
            StartPos = tok.EndPos;
            EndPos = tok.EndPos; // set the tokenizer to the new scan position
            return tok;
        }

        /// <summary>
        /// returns token with longest best match
        /// </summary>
        /// <returns></returns>
        public Token LookAhead(params TokenType[] expectedtokens)
        {
            int i;
            int startpos = StartPos;
            Token tok = null;
            List<TokenType> scantokens;


            // this prevents double scanning and matching
            // increased performance
            if (LookAheadToken != null 
                && LookAheadToken.Type != TokenType._UNDETERMINED_ 
                && LookAheadToken.Type != TokenType._NONE_) return LookAheadToken;

            // if no scantokens specified, then scan for all of them (= backward compatible)
            if (expectedtokens.Length == 0)
                scantokens = Tokens;
            else
            {
                scantokens = new List<TokenType>(expectedtokens);
                scantokens.AddRange(SkipList);
            }

            do
            {

                int len = -1;
                TokenType index = (TokenType)int.MaxValue;
                string input = Input.Substring(startpos);

                tok = new Token(startpos, EndPos);

                for (i = 0; i < scantokens.Count; i++)
                {
                    Regex r = Patterns[scantokens[i]];
                    Match m = r.Match(input);
                    if (m.Success && m.Index == 0 && ((m.Length > len) || (scantokens[i] < index && m.Length == len )))
                    {
                        len = m.Length;
                        index = scantokens[i];  
                    }
                }

                if (index >= 0 && len >= 0)
                {
                    tok.EndPos = startpos + len;
                    tok.Text = Input.Substring(tok.StartPos, len);
                    tok.Type = index;
                }
                else if (tok.StartPos < tok.EndPos - 1)
                {
                    tok.Text = Input.Substring(tok.StartPos, 1);
                }

                if (SkipList.Contains(tok.Type))
                {
                    startpos = tok.EndPos;
                    Skipped.Add(tok);
                }
                else
                {
                    // only assign to non-skipped tokens
                    tok.Skipped = Skipped; // assign prior skips to this token
                    Skipped = new List<Token>(); //reset skips
                }
            }
            while (SkipList.Contains(tok.Type));

            LookAheadToken = tok;
            return tok;
        }
    }

    #endregion

    #region Token

    public enum TokenType
    {

            //Non terminal tokens:
            _NONE_  = 0,
            _UNDETERMINED_= 1,

            //Non terminal tokens:
            Start   = 2,
            Circuit = 3,
            Colorcommand= 4,
            Piececommand= 5,
            Tubedescription= 6,
            Injectordescription= 7,
            Capdescription= 8,
            Position= 9,
            Timecommand= 10,
            Tagscommand= 11,
            Intset  = 12,
            Injectioncommand= 13,

            //Terminal tokens:
            ALIGNMENT= 14,
            UINT    = 15,
            INT     = 16,
            UFLOAT  = 17,
            AXIS    = 18,
            COLOR   = 19,
            PIECE   = 20,
            TUBE    = 21,
            CAP     = 22,
            INJECTOR= 23,
            IGNOREDSTUFF= 24,
            END     = 25,
            EOF     = 26,
            TIME    = 27,
            SIGN    = 28,
            INJECTION= 29,
            TAGS    = 30,
            BROPEN  = 31,
            BRCLOSE = 32,
            COMMA   = 33,
            WHITESPACE= 34
    }

    public class Token
    {
        private int startpos;
        private int endpos;
        private string text;
        private object value;

        // contains all prior skipped symbols
        private List<Token> skipped;

        public int StartPos { 
            get { return startpos;} 
            set { startpos = value; }
        }

        public int Length { 
            get { return endpos - startpos;} 
        }

        public int EndPos { 
            get { return endpos;} 
            set { endpos = value; }
        }

        public string Text { 
            get { return text;} 
            set { text = value; }
        }

        public List<Token> Skipped { 
            get { return skipped;} 
            set { skipped = value; }
        }
        public object Value { 
            get { return value;} 
            set { this.value = value; }
        }

        [XmlAttribute]
        public TokenType Type;

        public Token()
            : this(0, 0)
        {
        }

        public Token(int start, int end)
        {
            Type = TokenType._UNDETERMINED_;
            startpos = start;
            endpos = end;
            Text = ""; // must initialize with empty string, may cause null reference exceptions otherwise
            Value = null;
        }

        public void UpdateRange(Token token)
        {
            if (token.StartPos < startpos) startpos = token.StartPos;
            if (token.EndPos > endpos) endpos = token.EndPos;
        }

        public override string ToString()
        {
            if (Text != null)
                return Type.ToString() + " '" + Text + "'";
            else
                return Type.ToString();
        }
    }

    #endregion
}
